CREATE TABLE IF NOT EXISTS PUBLIC.HIGH_SCORE
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SCORE BIGINT,
    PLAYERNAME VARCHAR(255),
    DATE_DELETED TIMESTAMP
);

INSERT INTO PUBLIC.HIGH_SCORE (SCORE, PLAYERNAME)
VALUES (1, 'Player1');
INSERT INTO PUBLIC.HIGH_SCORE (SCORE, PLAYERNAME)
VALUES (3, 'Player2');
INSERT INTO PUBLIC.HIGH_SCORE (SCORE, PLAYERNAME)
VALUES (2, 'Player3');
INSERT INTO PUBLIC.HIGH_SCORE (SCORE, PLAYERNAME)
VALUES (1, 'Player4');